# Generated by Django 4.2.1 on 2023-05-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_driverresponse_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverresponse',
            unique_together={('order', 'driver')},
        ),
    ]
